
export struct Operations {
    subscribe: bool,
    get: bool,
    set: bool,
    toggle: bool,
}

export enum ValueKind { bool, int, float, string }
export enum RangeBoundType { open, included, excluded }
export struct RangeBound {
    type: RangeBoundType,
    value: int}

export struct ValueType {
    kind: ValueKind,
    optional: bool,
    string_values: [string],
    int_range: { start: RangeBound, end: RangeBound},
}

export struct Field {
    name: string,
    description: string,
    operations: Operations,
    value_type: ValueType,
}

export struct Device {
    id: string,
    name: string,
    description: string,
    fields: [Field]
}
