
import { SplashPage } from "splash.slint";
import { MainContent, NavigationController } from "navigation.slint";
import { DeviceListAdapter } from "devices/list.slint";
import { DeviceViewAdapter } from "devices/view.slint";
import { FieldListAdapter } from "devices/fields/list.slint";
import { AppBar, MaterialWindow } from "@material";
export { DeviceListAdapter, DeviceViewAdapter, FieldListAdapter }

export struct SavedConfig {
    server: string,
}

export component App inherits MaterialWindow {
    title: "Home Control";
    preferred-height: 1000px;
    preferred-width: 1500px;
    default-font-size: 15px;

    callback connect(string);
    property <bool> connected;
    in property <SavedConfig> config;
    in property <string> connection_error;
    public function connection_ready() {
        connected = true;
        NavigationController.device-list();
    }

    AppBar {
        title: "Home Control";
        y: 0;
        width: parent.width;
        show_background: true;
        leading_button: {
            icon: @image-url("../../material-1.0/ui/icons/arrow_back.svg"),
            tooltip: "Back",
            enabled: NavigationController.back-available
        };
        leading_button_clicked => {
            NavigationController.go-back();
        }
    }

    if !connected: SplashPage {
        server_selected(server) => {
            connect(server)
        }
        connection_error: connection_error;
        configured_server: config.server;
    }
    if connected: MainContent { }
}
