
import { DeviceView, DeviceViewAdapter } from "devices/view.slint";
import { Device } from "devices/models.slint";
import { DeviceList, DeviceListAdapter } from "devices/list.slint";

export enum Page { device-list, device-view }

export global NavigationController {
    out property <Page> current-page;
    out property <bool> back-available: current-page == Page.device-view;

    callback back;
    
    public function go-back() {
        if current-page == Page.device-view {
            device-list()
        }
    }
    
    public function device-list() {
        DeviceListAdapter.load_devices();
        self.current-page = Page.device-list;
    }

    public function device-view-by-id(id: string) {
        DeviceViewAdapter.loaded = false;
        DeviceViewAdapter.load_device(id);
        self.current-page = Page.device-view;
    }

    public function device-view(device: Device) {
        DeviceViewAdapter.device = device;
        DeviceViewAdapter.loaded = true;
        self.current-page = Page.device-view;
    }
}

export component MainContent {
    if NavigationController.current-page == Page.device-list: DeviceList {
        view-device(device) => {
            NavigationController.device-view(device)
        }
    }
    if NavigationController.current-page == Page.device-view: DeviceView { }
}
