
import { Field, ValueType, ValueKind } from "../models.slint";
import { Switch } from "@material";

export struct BoolValue {
    loaded: bool,
    null: bool,
    value: bool,
}

export global FieldListAdapter {
    in property <string> device-id;
    in property <bool> loaded;
    in property <[Field]> fields;
    out property <[BoolValue]> bool-values;
    // signal the backend to fetch the field value
    callback get-field-value(int, string);
    // signal the backend to set the field value
    callback set-bool-field-value(string, bool);
    
    public function update-bool-value(index: int, value: BoolValue) {
        bool-values[index] = value;
    }
}

component BoolFieldValue {
    in property <Field> field;
    in property <int> index;
    property <BoolValue> value: FieldListAdapter.bool-values[index];

    Switch {
        checked: value.value;
        enabled: value.loaded;
    }
}

// component IntValue {
//     in property <Field> field;
// }

// component FloatValue {
//     in property <Field> field;
// }

// component StringValue {
//     in property <Field> field;
// }

component FieldValue {
    in property <Field> field;
    in property <int> index;
    in property <bool> ready;
    callback get-bool-value;
    callback set-bool-value(bool);
    
    changed ready => {
        get-bool-value()
    }

    if field.value-type.optional: Text {
        text: "TODO: render optional values";
    }
    if field.value-type.kind == ValueKind.bool: BoolFieldValue {
        field: field;
    }
    // if field.value-type.kind == ValueKind.int: IntValue {
    //     field: field;
    // }
    // if field.value-type.kind == ValueKind.float: FloatValue {
    //     field: field;
    // }
    // if field.value-type.kind == ValueKind.string: StringValue {
    //     field: field;
    // }
}

export component FieldList inherits GridLayout {
    in property <[Field]> fields;
    in property <string> device-id;
    property <bool> ready: false;

    init => {
        FieldListAdapter.device-id = device-id;
        FieldListAdapter.loaded = false;
        FieldListAdapter.fields = fields;
        ready = true;
    }

    Text {
        text: "Field Name";
        font-weight: 550;
    }

    Text {
        text: "Value";
        font-weight: 550;
    }

    for field[i] in fields: Text {
        text: field.name;
        row: i+1;
        col: 0;
    }

    for field[i] in fields: FieldValue {
        index: i;
        field: field;
        row: i+1;
        col: 1;
        ready: ready;
        get-bool-value => {
            FieldListAdapter.get-field-value(i, field.name)
        };
        set-bool-value(value) => {
            FieldListAdapter.set-bool-field-value(field.name, value)
        }
    }
}
